source 'https://rubygems.org'

gem 'capybara', '~> 3.33'
gem 'rspec', '~> 3.8' # Released: August 4, 2018
gem 'selenium-webdriver', '~> 3.141' # Released: November 1, 2018
gem 'ffi', '~> 1.13', '>= 1.13.1'
